service: hms-email-service

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
